apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java
  namespace: kube-logging
spec:
  env:
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: none
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector.kube-logging.svc:4317
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "20"
    - name: OTEL_TRACES_SAMPLER
      value: parentbased_traceidratio
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.85"
    - name: SPLUNK_TRACE_RESPONSE_HEADER_ENABLED
      value: "true"
  exporter:
    endpoint: http://otel-collector.kube-logging.svc:4317
  propagators:
    - jaeger
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:{AGENT_VERSION}
    env:
    - name: OTEL_JAVAAGENT_DEBUG
      value: "true"
    - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
      value: "false"
    - name: SPLUNK_PROFILER_ENABLED
      value: "false"
