apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-service-account
  namespace: kube-logging
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: kube-logging
  labels:
    app: opensearch
spec:
  type: ClusterIP
  selector:
    app: opensearch
  ports:
    - port: 9200
      protocol: TCP
      name: http
    - port: 9300
      protocol: TCP
      name: transport
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: os-cluster
  namespace: kube-logging
spec:
  serviceName: opensearch
  selector:
    matchLabels:
      app: opensearch
  replicas: 1
  template:
    metadata:
      name: opensearch
      labels:
        app: opensearch
    spec:
      serviceAccount: opensearch-service-account
      containers:
      - name: opensearch
        image: docker.io/opensearchproject/opensearch:1.2.3
        imagePullPolicy: "IfNotPresent"
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        resources:
          limits:
            cpu: 500m
            memory: 3000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
        - name: config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: security-config
          mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
          subPath: config.yml
          readOnly: true
        - name: opensearch-cert
          mountPath: /usr/share/opensearch/config/certificates
          readOnly: true
        - name: admin-cert
          mountPath: /usr/share/opensearch/config/certificates/admin
          readOnly: true
        #- name: hyperauth-ca
        #  mountPath: /usr/share/opensearch/config/certificates/hyperauth
        #  readOnly: true
        env:
          - name: cluster.name
            value: os-cluster
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "os-cluster-0.opensearch" #"os-cluster-0.opensearch,os-cluster-1.opensearch,os-cluster-2.opensearch"
          - name: cluster.initial_master_nodes
            value: "os-cluster-0" #"os-cluster-0,os-cluster-1,os-cluster-2"
          - name: OPENSEARCH_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
      initContainers:
      - name: fix-permissions
        image: busybox:1.32.0
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/opensearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
      - name: increase-vm-max-map
        image: busybox:1.32.0
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true 
      - name: increase-fd-ulimit
        image: busybox:1.32.0
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      volumes:
      - name: config
        configMap:
          name: opensearch-config
      - name: security-config
        configMap:
          name: opensearch-securityconfig
      - name: opensearch-cert
        secret:
          secretName: opensearch-secret
      - name: admin-cert
        secret:
          secretName: admin-secret
      #- name: hyperauth-ca
      #  secret:
      #    secretName: hyperauth-ca
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: opensearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  namespace: kube-logging
  labels:
    app: opensearch
data:
  opensearch.yml: |
    cluster.name: "os-cluster"
    network.host: "0.0.0.0"
    discovery.seed_hosts: os-cluster-0.opensearch
    cluster.initial_master_nodes: os-cluster-0

    plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/certificates/tls.key
    plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/certificates/tls.crt
    plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/certificates/ca.crt
    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/certificates/tls.key
    plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/certificates/tls.crt
    plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/certificates/ca.crt
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true

    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    plugins.security.authcz.admin_dn:
      - "CN=admin"
    plugins.security.nodes_dn:
      - "CN=opensearch"
    compatibility.override_main_response_version: true
    plugins.security.system_indices.indices:
            [
              ".opendistro-alerting-config",
              ".opendistro-alerting-alert*",
              ".opendistro-anomaly-results*",
              ".opendistro-anomaly-detector*",
              ".opendistro-anomaly-checkpoints",
              ".opendistro-anomaly-detection-state",
              ".opendistro-reports-*",
              ".opendistro-notifications-*",
              ".opendistro-notebooks",
              ".opendistro-asynchronous-search-response*",
            ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-securityconfig
  namespace: kube-logging
  labels:
    app: opensearch
data:
  config.yml: |
    _meta:
       type: "config"
       config_version: 2
    config:
      dynamic:
        authc:
          basic_internal_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: basic
              challenge: false
            authentication_backend:
              type: internal
          openid_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: "openid"
              challenge: false
              config:
                subject_key: preferred_username
                roles_key: roles
                openid_connect_url: https://{HYPERAUTH_URL}/auth/realms/tmax/.well-known/openid-configuration
                openid_connect_idp:
                  enable_ssl: true
                  verify_hostnames: false
                  pemtrustedcas_filepath: /usr/share/opensearch/config/certificates/hyperauth/ca.crt
            authentication_backend:
              type: noop
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-cert
  namespace: kube-logging
spec:
  secretName: admin-secret
  commonName: admin
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-cert
  namespace: kube-logging
spec:
  secretName: opensearch-secret
  commonName: "opensearch"
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "tmax-cloud"
    - "opensearch.kube-logging.svc"
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer
---
apiVersion: v1
kind: Secret
metadata:
  name: hyperauth-ca
  namespace: kube-logging
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIRAMv5gYRn62NbTeGZTUjw7sswDQYJKoZIhvcNAQELBQAw
    FDESMBAGA1UEAxMJdG1heGNsb3VkMB4XDTIyMDExOTA1NTA1OVoXDTIzMDExOTA1
    NTA1OVowFDESMBAGA1UEAxMJdG1heGNsb3VkMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAlRGRMIFCZ14+BgY/l12HIgNBaOuHLYX8owaqFWGuF3APLbHY
    vddwmgg0Tll6h0rCLkIFVrzQmFYmbyU2+M6JRMajyMWWnuCAtEqpN1ZwDm4RnZfs
    i5OyFmJKZ3LcmKqIkmyaYb2QqdTliNQkqytUmyX59zkrTe2Y/sWkPGA3jKTm9CIK
    7l9x5E8JfJ3VKy289DzLjcTIX0AeRgd2HMdpN6DFAouTBhzMa8OqO3Dq0pSvqwju
    Wr47nqujAIu+7RgxfEcCzx36GmH7sJpCUZzKCfEqcA65IjgpQJWARGtoDZHJ767K
    i5O7lDc8qkPdZRDT+XoHfzMTSYcmKh8Lg4X8AwIDAQABo2EwXzAOBgNVHQ8BAf8E
    BAMCAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQF
    MAMBAf8wHQYDVR0OBBYEFL6/kFBtiDyVKwxAGYIwbLH9dG4rMA0GCSqGSIb3DQEB
    CwUAA4IBAQAQAP9JRV3cv0owTl1tH+af7Fbf1hk/8IuT0ZWE+r3W9VEYlVV+i1D5
    hWOfLRmaKp9BHATKiz8e4buoYtRv0mhk8oWtw1BaGPBiYH/1rGfz97vTgMnkkFaH
    iSq7QO6xtzJLYK8wcv/ndpyU2qI/mZzPC4a3jmnMh/ogMVahZ5ByqaMgiQ5HMhJl
    PkZl50o+xILFVHFJgzNIm5ShDag8gKZ9HWieh50Ks/vFHZl99kCtgLQ8fXuapys3
    piJ00dEOHZoBqjb2AjoCDSkAScHvufLNfcdHKF4ln4aP3LlRBmUX53hYJYJhaDAU
    R8mmeoP6Xz6IQFTwkGXaKuP11txXLFjx
    -----END CERTIFICATE-----

