apiVersion: v1
kind: Secret
metadata:
  name: hyperauth-ca
  namespace: kube-logging
type: Opaque
stringData:
  # hyperauth 네임스페이스의 hyperauth-https-secret에 있는 ca.crt 붙여넣기
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIRAMv5gYRn62NbTeGZTUjw7sswDQYJKoZIhvcNAQELBQAw
    
    
    
    
    ...
    
    
    
    
    
    R8mmeoP6Xz6IQFTwkGXaKuP11txXLFjx
    -----END CERTIFICATE-----
