apiVersion: v1
kind: Secret
metadata:
  name: hyperauth-ca
  namespace: kube-logging
type: Opaque
stringData:
  # api-gateway-system 네임스페이스의 gateway-tls-acme에 있는 tls.crt 붙여넣기
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDFDCCAfygAwIBAgIRAMv5gYRn62NbTeGZTUjw7sswDQYJKoZIhvcNAQELBQAw
    
    
    
    
    ...
    
    
    
    
    
    R8mmeoP6Xz6IQFTwkGXaKuP11txXLFjx
    -----END CERTIFICATE-----
